name: Security

on:
  schedule:
    - cron: '0 9 * * 1'
  pull_request:
    branches: [ main ]

jobs:
  security:
    uses: selfshop-dev/platform/.github/workflows/security.yml@v1
    permissions:
      security-events: write
      contents: read
      actions: read